<a href="https://colab.research.google.com/github/briskicedteaa/Machine-Learning-for-Molecular-Data/blob/main/Train_Test_Splits.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
from sklearn.model_selection import train_test_split
import pandas as pd

In [4]:
df = pd.read_csv('/content/Ligands2.csv', sep =';' )
df = df.drop(columns=df.columns.difference(['Ligand Efficiency LE', 'Ligand Efficiency LLE', 'Ligand Efficiency BEI', 'Ligand Efficiency SEI', 'Molecular Weight', 'Standard Value', 'AlogP']))
df = df.dropna()
df

,Molecular Weight,AlogP,Standard Value,Ligand Efficiency BEI,Ligand Efficiency LE,Ligand Efficiency LLE,Ligand Efficiency SEI
0,472.67,4.21,60.00,15.28,0.29,3.01,12.61
8,323.39,3.29,657.00,19.12,0.35,2.89,15.95
9,413.52,5.25,22300.00,11.25,0.20,-0.60,12.00
10,379.50,4.36,7.00,21.49,0.40,3.79,21.03
13,427.55,3.69,280.00,15.33,0.28,2.86,6.84
...,...,...,...,...,...,...,...
20124,351.35,3.88,1670.00,16.44,0.33,1.90,12.09
20125,433.49,7.26,7.10,18.80,0.36,0.89,22.05
20126,471.59,8.33,70.00,15.17,0.30,-1.18,19.36
20128,539.81,7.45,7.63,15.04,0.30,0.67,20.94
20131,455.41,5.43,308.90,14.30,0.32,1.08,11.72

In [6]:
x = df[
[
'Molecular Weight',
'AlogP',
'Ligand Efficiency BEI',
'Ligand Efficiency LE',
'Ligand Efficiency LLE',
'Ligand Efficiency SEI'
]
]

y = df['Standard Value']

In [7]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=4
)
x_train

,Molecular Weight,AlogP,Ligand Efficiency BEI,Ligand Efficiency LE,Ligand Efficiency LLE,Ligand Efficiency SEI
9110,379.50,4.36,21.08,0.39,3.64,20.63
12002,454.96,5.84,9.45,0.18,-1.54,10.17
8165,457.67,4.67,16.62,0.31,2.94,21.96
7696,322.41,4.12,17.34,0.32,1.47,14.52
350,210.28,3.18,35.67,0.64,4.32,19.28
...,...,...,...,...,...,...
15347,379.50,4.36,20.62,0.38,3.46,20.18
1553,544.87,4.88,16.51,0.32,2.80,13.59
6397,348.41,3.25,14.61,0.27,1.84,5.59
367,275.35,1.77,28.05,0.53,5.95,17.24
2634,337.42,3.67,16.17,0.30,1.79,12.18